[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc = "0.8.13"
auto_detect_solc = false
# Increase optimizer_runs
optimizer = true
optimizer_runs = 10_000_000
# Fuzz more than the default 256
fuzz = { runs = 1_000 }

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz = { runs = 100_000 }
